### ISSUE TITLE
ignore参数不能填style.scss之类的吗

### ISSUE THREAD

**Issue by 1549469775** [Qymh/vue-router-invoke-webpack-plugin#25]
**Describe the bug**
如题，填了就报错
![image](https://user-images.githubusercontent.com/20150696/72119619-fd3a0780-338f-11ea-9aaf-4b7acab71228.png)

**Version**
`vue-router-invoke-webpack-plugin`: 0.4.1
`webpack-cli`: 3.3.10
`node`: 10.15.3
`system`: windows 

** The tree of files or Screenshots**

[example of tree]

```
src
├── views
│   ├── Login
│   │   └── Index.vue
│   │   └── Style.scss
│   └── User
│       ├── Account
│       │   └── Index.vue
│       ├── Home
│       │   └── Index.vue
│       └── Index.vue
```

**Comment by 1549469775** [comment]
我想把样式单独拆出来

**Comment by Qymh** [comment]
0.4.3 更新一哈 [ignore支持正则匹配](https://github.com/Qymh/vue-router-invoke-webpack-plugin/blob/dev/docs/zh_CN/README.md#%E5%BF%BD%E7%95%A5%E6%96%87%E4%BB%B6%E5%92%8C%E6%96%87%E4%BB%B6%E5%A4%B9) @1549469775

**Comment by 1549469775** [comment]
哈哈，谢谢，可以了。

**Comment by Qymh** [comment]
么事么事~
