### ISSUE TITLE
一个嵌套路由下不能再出现多个嵌套路由了，使用的是源码中的例子，其它无任何改动

### ISSUE THREAD

**Issue by zhujixiang-yuxi** [Qymh/vue-router-invoke-webpack-plugin#27]
**Describe the bug**

**Version**
`vue-router-invoke-webpack-plugin`:
`webpack`:
`node`:
`system`: [windows or mac]

** The tree of files or Screenshots**

[example of tree]

```
![image](https://user-images.githubusercontent.com/43059503/75351849-c0948200-58e3-11ea-8b10-53adc034595a.png)

**Comment by Qymh** [comment]
fixed in 0.4.4 @zhujixiang-yuxi
