### ISSUE TITLE
restful 风格路由中，路由参数怎么配？

### ISSUE THREAD

**Issue by gaollard** [Qymh/vue-router-invoke-webpack-plugin#35]
**Describe the bug**
restful 风格路由中，路由参数怎么配？

```js
export default new Router({
  routes: [
    {
      name: 'M1',
      component: Product,
      path: '/product/:id',
      meta: {
        title: '商品详情'
      }
    }
  ]
});
```

**Comment by Qymh** [comment]
- 路径

```tree
product
├── _id
│   ├── index.vue
│   └── meta.yml
└── index.vue
```

- meta.yml

```yaml
meta:
  - title: '商品详情'
```

- 生成的文件

```js
  {
    component: () => import('@/src/product/index.vue'),
    name: 'product',
    path: '/product',
  },
  {
    component: () => import('@/src/product/_id/index.vue'),
    name: 'product-id',
    meta: {
      title: '商品详情',
    },
    path: '/product/:id',
  },
```

**Comment by gaollard** [comment]
> * 路径
> 
> ```
> product
> ├── _id
> │   ├── index.vue
> │   └── meta.yml
> └── index.vue
> ```
> 
> * meta.yml
> 
> ```yaml
> meta:
>   - title: '商品详情'
> ```
> 
> * 生成的文件
> 
> ```js
>   {
>     component: () => import('@/src/product/index.vue'),
>     name: 'product',
>     path: '/product',
>   },
>   {
>     component: () => import('@/src/product/_id/index.vue'),
>     name: 'product-id',
>     meta: {
>       title: '商品详情',
>     },
>     path: '/product/:id',
>   },
> ```

ths

**Comment by gaollard** [comment]
> * 路径
> 
> ```
> product
> ├── _id
> │   ├── index.vue
> │   └── meta.yml
> └── index.vue
> ```
> 
> * meta.yml
> 
> ```yaml
> meta:
>   - title: '商品详情'
> ```
> 
> * 生成的文件
> 
> ```js
>   {
>     component: () => import('@/src/product/index.vue'),
>     name: 'product',
>     path: '/product',
>   },
>   {
>     component: () => import('@/src/product/_id/index.vue'),
>     name: 'product-id',
>     meta: {
>       title: '商品详情',
>     },
>     path: '/product/:id',
>   },
> ```

ths
